tinycompress: add do_configure depends on virtual/kernel:do_shared_workdir
Adding depends on virtual/kernel:do_shared_workdir to ensure that the
work-shared/kernel-build-articafts/ uapi headers are always populated
before tinycompress recipe compiles.

  src/lib/compress.c: In function 'compress_set_next_track_param':
  src/lib/compress.c:584:26: error: 'SNDRV_COMPRESS_SET_NEXT_TRACK_PARAM'
    undeclared (first use in this function); did you mean 'SNDRV_COMPRESS_NEXT_TRACK'?
      if (ioctl(compress->fd, SNDRV_COMPRESS_SET_NEXT_TRACK_PARAM, codec_options))
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              SNDRV_COMPRESS_NEXT_TRACK

Change-Id: I7842d5c6979dce512893a02bcec1b0b8a7e5e44e